baseURL = ""
languageCode = "en-us"
theme = "SimpleIntro"
title = "Portfolio"
publishDir = "public"

[params]
    mainbg = "https://picsum.photos/1920/1080"
    name = "Justin Galang"
    mainTitle = "Justin Galang"
    mainText = "Software Developer | Entepreneur"

[menus]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "#about"
    [[menu.main]]
        identifier = "skills"
        name = "Skills"
        url = "#skills"
    [[menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "#projects"
